name: Deploy PR-Preview
on:
  workflow_run:
    workflows: ["Build PR-Preview"]
    types:
      - completed
permissions:
  contents: write
  pages: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Approval Status
        id: approval_check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(echo "${{ github.event.workflow_run.pull_requests[0].number }}")
          APPROVALS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/reviews" | \
            jq '[.[] | select(.state == "APPROVED" and (.user.type == "User"))] | length')
          if [ "$APPROVALS" -eq 0 ]; then
            echo "No valid approval found. Exiting."
            exit 1
          fi

      - uses: actions/download-artifact@v4
        if: success()
        with:
          name: github-pages
          path: build/
          github-token: ${{github.token}}
          repository: ${{github.repository}}
          run-id: ${{github.event.workflow_run.id}}

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-deploy
          build_dir: build/
          commit_message: "Deploy to Github Pages"
          jekyll: false
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
