name: Deploy PR-Preview
on:
  workflow_run:
    workflows: ["Build PR-Preview"]
    types:
      - completed
permissions:
  contents: write
  pages: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download PR Number Artifact
        uses: actions/download-artifact@v2
        with:
          name: pr-number
          path: .

      - name: Check PR Approval Status
        id: approval_check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$$(cat pr_number.txt)

          if [ -z "$PR_NUMBER" ]; then
            echo "Error: PR number is empty. Exiting."
            exit 1
          fi

          RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/reviews")

          if ! echo "$RESPONSE" | jq . > /dev/null 2>&1; then
            echo "Error: Invalid JSON response from GitHub API."
            exit 1
          fi

          APPROVALS=$(echo "$RESPONSE" | jq '[.[] | select(.state == "APPROVED" and (.user.type == "User"))] | length')
          echo "Approvals found: $APPROVALS"

          if [ "$APPROVALS" -eq 0 ]; then
            echo "No valid approval found. Exiting."
            exit 1
          fi

      - uses: actions/download-artifact@v4
        if: success()
        with:
          name: github-pages
          path: build/
          github-token: ${{github.token}}
          repository: ${{github.repository}}
          run-id: ${{github.event.workflow_run.id}}

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-deploy
          build_dir: build/
          commit_message: "Deploy to Github Pages"
          jekyll: false
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
