name: Build and Publish Storybook to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16.19.0"

      - name: Install Dependencies
        run: yarn

      - name: Build Storybook
        run: yarn build:storybook
        working-directory: packages/react

      - name: Build UI-Elements
        run: yarn build:storybook
        working-directory: packages/ui-elements

      - name: Prepare Build Folder
        run: |
          mkdir -p build
          mv -v packages/react/storybook-static/* build/
          mkdir -p build/ui-elements
          mv -v packages/ui-elements/storybook-static/* build/ui-elements/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          publish_dir: build
